spring:
  application:
    name: project
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_DOMAIN}:3306/db_daengdaeng_eodiga_core?&rewriteBatchedStatements=true
    username: root
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET}
            redirect-uri: "https://${DOMAIN}:8080/login/oauth2/code/google"
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_OAUTH_ID}
            client-secret: ${KAKAO_OAUTH_SECRET}
            redirect-uri: "http://${DOMAIN}:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  jwt:
    secret: ${SECURITY_SECRET}


  data:
    redis:
      host: ${REDIS_DOMAIN}
      port: 6379
      password: ${REDIS_PWD}

  kakao:
    api:
      url: "https://dapi.kakao.com/v2/${DOMAIN}/geo/coord2address.json"
      key: ${KAKAO_REST_API_KEY}