spring:
  application:
    name: project
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/db_daengdaeng_eodiga_core?&rewriteBatchedStatements=true
    username: root
    #password: ${MYSQL_PWD}
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
